name: 'Create .env file'
description: 'GitHub Action to create a .env file with GitHub Secrets & Infisical'
author: 'Creatrip'
branding:
  icon: 'briefcase'
  color: 'gray-dark'

inputs:
  file_name:
    description: 'The filename for the envfile'
    default: '.env'
  directory:
    description: 'The directory to put the envfile in'
    default: ''
  token:
    description: 'The infisical token to use'
    required: true
  environment:
    description: 'The infisical environment to use'
    required: true

runs:
  using: 'node16'
  main: 'build/index.js'
